### ISSUE TITLE
Strong classical simulation

### ISSUE THREAD

**Issue by bichselb** [Quantomatic/quizx#7]
Hi

I would like to use this implementation for strong classical simulation, as discussed in [here](https://arxiv.org/abs/2109.01076).

I am not quite sure how I have to proceed. Assuming I have a QASM circuit in a text file, I assume I can use functions [load](https://github.com/Quantomatic/quizx/blob/59a9a60ae6018c729e3316d4ea6416ed9604757e/pybindings/src/lib.rs#L64) and [to_graph](https://github.com/Quantomatic/quizx/blob/59a9a60ae6018c729e3316d4ea6416ed9604757e/pybindings/src/lib.rs#L69) to obtain the corresponding `VecGraph`.

But how do I get the probability of a given output? I assume I have to use [full_simp](https://github.com/Quantomatic/quizx/blob/master/quizx/src/simplify.rs#L233) somehow, but do not know how to get a number from it, or how to specify which output probability I am looking for.

Thanks for your help!

**Comment by akissinger** [comment]
Hi,

It's the `Decomposer` you want for computing amplitudes (or probabilities). Have a look at the code in `bin/` for some examples (e.g. things named "hidden shift" or "pauli gadget").

In summary: load a circuit and convert it to a graph with `to_graph`. Then, you can plug bra's and ket's into the inputs/outputs of a graph using the `plug_inputs` and `plug_outputs` methods, pass that graph to the decomposer, then retrieve the scalar:

```rust
g.plug_inputs(&vec![BasisElem::Z0; 20]);
g.plug_outputs(&vec![BasisElem::Z0; 20]);
let mut d = Decomposer::new(&g);
d.with_full_simp(); // set simplification method to full_simp
// optionally adjust some other parameters...
d.decomp_all();
println!("<0..0|C|0..0> = {}", d.scalar.float_value());
```

**Comment by bichselb** [comment]
Thanks so much, this works!
